### PR TITLE
created a temporary file, so that the build directory will exist when…

### PR DESCRIPTION
**Pull request by flyingbarron**
… the repo is first cloned.

### CODE REVIEW

**Comment by artyom-beilis** [comment]
Usually build directory does not exists for a reason. User can give whatever name he wants to for example `build_debug` for android it includes arch name.

If the directory exists it make confuse experienced user.

**Comment by flyingbarron** [comment]
1. An experienced user will be able to read the readme and not be confused :) 
2. If it makes like easier for a new user, that will help turn the new user into an experienced user faster 
3. If you still don't want the file, then some documentation should be added to explain what's going on to a new user

**Comment by artyom-beilis** [comment]
You know how to you clean the build directory to restart from scratch?

```
cd build
rm -fr *
```

So no... sorry

**Comment by artyom-beilis** [comment]
The detailed docs are there: http://cppcms.com/wikipp/en/page/cppcms_1x_build

There is a huge wiki with all kind of stuff, for example Windows build: http://cppcms.com/wikipp/en/page/windows_msvc_build

**Pull request closed without merging**
